import { Story, Meta } from '@storybook/react/types-6-0';
import { FormButtonProps } from './FormButton';
declare const _default: Meta<import("@storybook/react/types-6-0").Args>;
export default _default;
export declare const DefaultButton: Story<FormButtonProps>;
export declare const DisabledDefaultButton: Story<FormButtonProps>;
export declare const DefaultLightButton: Story<FormButtonProps>;
export declare const BorderedLightButton: Story<FormButtonProps>;
export declare const CustomTextButton: Story<FormButtonProps>;
export declare const CustomButton: Story<FormButtonProps>;
export declare const ClickButton: Story<FormButtonProps>;
export declare const UnstyledButton: Story<FormButtonProps>;
