import { Story, Meta } from '@storybook/react/types-6-0';
import { FormInputProps } from './FormInput';
declare const _default: Meta<import("@storybook/react/types-6-0").Args>;
export default _default;
export declare const DefaultInput: Story<FormInputProps>;
export declare const InputWithLabel: Story<FormInputProps>;
export declare const InputWithHelper: Story<FormInputProps>;
export declare const DarkInputWithHelper: Story<FormInputProps>;
export declare const InputWithValidValue: Story<FormInputProps>;
export declare const DarkInputWithValidValue: Story<FormInputProps>;
export declare const InputWithValidFeedback: Story<FormInputProps>;
export declare const DarkInputWithValidFeedback: Story<FormInputProps>;
export declare const InputWithInvalidValue: Story<FormInputProps>;
export declare const DarkInputWithInvalidValue: Story<FormInputProps>;
export declare const InputWithInvalidFeedback: Story<FormInputProps>;
export declare const DarkInputWithInvalidFeedback: Story<FormInputProps>;
